version: '3'
services:
  app:
    build:
      context: .
      args:
        PORT: '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
  redis:
    image: redis:bullseye
    volumes:
      - /tmp/redis:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
