version: "3"
services:
    app:
        build: .
        ports:
            - "3308:3308"
        restart: unless-stopped
    redis:
        image: redis:buster
        ports:
            - "6379:6379"
        restart: unless-stopped
