name: Test and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testandlint:
    name: Unit tests and linting
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node: ['14', '16', '17', '18']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Run linter
        run: npm run linter
